version: '3.4'

services:
  users:
    image: users
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80     
    depends_on: 
      - db-postgres
    environment:
      - DB_USERNAME=test_app
      - DB_PASSWORD=Password4321
      - DB_URL=jdbc:postgresql://db-postgres:5432/postgres
     
  db-postgres:
    image: postgres:9.6
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=test_app
      - POSTGRES_PASSWORD=Password4321